sudo: required
services:
  - docker
before_install:
  # installing GCP SDK
  # this is the output of travis encrypt-file
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install and update kubectl
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  # what project and which zone
  - gcloud config set project multi-k8s-238909
  - gcloud config set compute/zone europe-west3-a
  - gcloud container clusters get-credentials multi-cluster
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t gcannata/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev

script:
  # to make test exit after running once remember to add -- --coverage
  - docker run gcannata/react-test npm run test -- --coverage 
